/// Flutter icons Coral
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Coral
///      fonts:
///       - asset: fonts/Coral.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Coral {
  Coral._();

  static const _kFontFam = 'Coral';

  static const IconData phone = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData facebook_1 = IconData(0xf09a, fontFamily: _kFontFam);
  static const IconData youtube_play = IconData(0xf16a, fontFamily: _kFontFam);
  static const IconData instagram = IconData(0xf16d, fontFamily: _kFontFam);
  static const IconData twitter_squared =
      IconData(0xf304, fontFamily: _kFontFam);
}
